#+STARTUP: overview nologdone
#+SEQ_TODO: TODO(t) NEXT(n) STARTED(s) WAITING(w) | DONE(d) OLD(o) CANCELLED(c)
#+TODO: MAYBE(m) FAILED(f) LOG(l) DEFERRED(e) BUG(b)
* MAYBE add SPECIAL locative and make variable an alias of it?
* MAYBE support DECLARATION docstrings?
* MAYBE support SETF docstring?
* MAYBE better SOURCE addressing for INCLUDE
* MAYBE the LAMBDA locative could evaluate its arguments
* MAYBE "function. FOO" should not consider FUNCTION a locative
"BAR has a useful function, FOO doesn't."
* MAYBE complete ASDF:SYSTEM and CLHS names case-insensitively?
Currently, MAP-NAMES-FOR-TYPE returns only the subset of names that
DREF:DREF allows. For example, MAP-NAMES-FOR-TYPE returns "Printer
Dispatching" but DREF allows case-insensitive substring matching:

(dref:dref "isPat" 'pax:clhs)
==> #<DREF:DREF "22.1.2" (MGL-PAX:CLHS MGL-PAX:SECTION)>

(dref:dref "printer di" 'pax:clhs)
==> #<DREF:DREF "22.1.2" (MGL-PAX:CLHS MGL-PAX:SECTION)>

But completing "printer di<TAB> doesn't work.

So, we need to pass PREFIX to MAP-NAMES or similar, but that won't
support fancier completion mechanisms such as c-p-c.

Instead, the completion may match case-insensitively but replace with
the canonical name?

Let MAP-NAMES-FOR-TYPE somehow specify whether matching is case-
sensitive?

There is always mgl-pax-apropos for case-insensitive matching.
* MAYBE add SYMBOL as an alias for dislocated?
* MAYBE add source locative
That is, link to GitHub, without documenting anything. Useful for code
examples without actually INCLUDEing them. Does/should LAMBDA do this?
* DONE compare DRef to the Definitions library
Pros of DRef:
- Supports string names (called designators in Definitions). PAX needs
  to distinguish those from symbol-based ones.
- Operations such as ARGLIST (~ DEFINITIONS:ARGUMENTS) can be
  specialized on normal objects for RESOLVEable definitions. In
  Definitions, operations are always specialized on a DEFINITION
  subclass, which can result in unnecessary duplication of the
  hierarchy.
- (LOCATE #'PRINT) is fast, the equivalent DEFINITIONS:WHO-DEFINES is
  very slow. DRef uses this to allow specialization of ARGLIST on
  either object or definition type.
- Can LOCATE a single unresolvable definition (e.g. (DREF 'XXX
  'VARIABLE)). Definitions only has WHO-DEFINES, which needs the
  OBJECT of the definition. Needed by PAX.
- DRef supports Swank buffer source locations when running under
  Slime. Needed by PAX.
- DRef has XREFs, which do not need even the locative type to be
  defined when they are created. Needed by PAX.
- DREF-APROPOS more flexible. Needed by PAX.
- ARGLIST returns the type of arglist.
- DOCSTRING returns the package if available. Needed by PAX.
- The DRef packages can be :USEd without conflicts with CL.
  Definitions shadows CL:SYMBOL, CL:PACKAGE, CL:CLASS, etc.
- DRef supports only 7 Lisps, Definitions 3.
- DRef has an extensive test suite. Definitions has no tests.
- DRef has extensive documentation.

Pros of Definitions:
- Definitions has BIND, (SETF OBJECT), UNBIND, (SETF DOCUMENTATION).
  These can be added to DRef if needed.
* MAYBE add DCAST and DLOOKUP locatives
Needs a constant name such as LOCATE* or DREF*.
