;;;; This file was generated by
;;;;
;;;;   (autoload:record-loaddefs "dref")
;;;;
;;;; Do not edit.

(in-package :cl)

(autoload:autoload dref-ext:make-source-location "dref/full" :arglist
                   "(&key dref::file file-position dref::buffer dref::buffer-position dref::snippet)"
                   :docstring
                   "Make a Swank source location. The ultimate reference is
  `slime-goto-source-location` in `slime.el`. When SNIPPET is
  provided, the match nearest to FILE-POSITION is determined (see the
  Elisp `slime-isearch` and SOURCE-LOCATION-ADJUSTED-FILE-POSITION).")

(autoload:autoload dref-ext:source-location-adjusted-file-position
                   "dref/full" :arglist "(dref::location)" :docstring
                   "Return the actual file position LOCATION points to allowing for
  some deviation from the raw SOURCE-LOCATION-FILE-POSITION, which is
  adjusted by searching for the nearest occurrence of
  SOURCE-LOCATION-SNIPPET in the file. The file is read using the same
  external format that ASDF would use to compile it. Needless to say,
  this can be a very expensive operation.

  If SOURCE-LOCATION-FILE is NIL, NIL is returned. If there is no
  snippet, or it doesn't match, then SOURCE-LOCATION-FILE-POSITION (or
  0 if that's NIL) is returned.

  This is a non-interactive companion to the Elisp function
  `slime-location-offset`, supporting only file positions and
  non-partial matching of snippets.")

(autoload:autoload dref-ext:source-location-buffer "dref/full" :arglist
                   "(dref::location)" :docstring
                   "Return the name of the Emacs buffer of the [defining form][clhs] or
  NIL if there is no such Emacs buffer.")

(autoload:autoload dref-ext:source-location-buffer-position "dref/full"
                   :arglist "(dref::location)" :docstring
                   "Return the position of the [defining form][clhs] in
  SOURCE-LOCATION-BUFFER or NIL if it's not available. The first
  position is 1.")

(autoload:autoload dref-ext:source-location-file "dref/full" :arglist
                   "(dref::location)" :docstring
                   "Return the name of the file of the [defining form][clhs].
  This may be NIL, for example, if LOCATION is of a [defining
  form][clhs] that was entered at the REPL, or compiled in the
  `*slime-scratch*` buffer.")

(autoload:autoload dref-ext:source-location-file-position "dref/full"
                   :arglist "(dref::location)" :docstring
                   "Return the file position of the [defining form][clhs] or NIL
  if it's not available. The first position is 0.")

(autoload:autoload dref-ext:source-location-p "dref/full" :arglist
                   "(dref::object)" :docstring
                   "See if OBJECT is a source location object.")

(autoload:autoload dref-ext:source-location-snippet "dref/full" :arglist
                   "(dref::location)" :docstring
                   "Return the [defining form][clhs] or a prefix of it as a string or NIL
  if it's not available.")

(autoload:autoload dref::ensure-dref-loaded "dref/full" :arglist "nil")

(autoload:autoload dref:accessor-slot-definition "dref/full" :arglist
                   "(dref:dref)" :docstring
                   "Return the SLOT-DEFINITION object corresponding to DREF, which may
  denote a READER, a WRITER or an ACCESSOR.")

(autoload:autoload dref:definitions "dref/full" :arglist
                   "(dref::name &key (dref:dtype t) (sort t))" :docstring
                   "List all definitions of NAME that are of DTYPE as [DREFs][class].

  Just as `(DREF NAME LOCATIVE)` returns the canonical definition, the
  DREF-NAMEs of returned by DEFINITIONS may be different from NAME:

  ```cl-transcript
  (definitions \"PAX\")
  ==> (#<DREF \"MGL-PAX\" PACKAGE>)
  ```

  ```cl-transcript
  (definitions 'mgl-pax)
  ==> (#<DREF \"MGL-PAX\" PACKAGE> #<DREF \"mgl-pax\" ASDF/SYSTEM:SYSTEM>)
  ```

  Similarly, DREF-LOCATIVE-TYPE may be more made more specific:

  ```cl-transcript
  (definitions 'dref:locate-error :dtype 'type)
  ==> (#<DREF LOCATE-ERROR CONDITION>)
  ```

  If SORT, the returned list is ordered according to SORT-REFERENCES.

  Can be extended via MAP-DEFINITIONS-OF-NAME.")

(autoload:autoload dref:dref-apropos "dref/full" :arglist
                   "(dref::name &key package dref::external-only dref::case-sensitive (dref:dtype t) (sort t))"
                   :docstring
                   "Return a list of [DREF][class]s corresponding to existing
  definitions that match the various arguments. First, `(DREF-APROPOS
  NIL)` lists all definitions in the running Lisp and maybe more (e.g.
  [MGL-PAX:CLHS][locative]). Arguments specify how the list of
  definitions is filtered.

  DREF-APROPOS itself is similar to CL:APROPOS-LIST, but

  - it finds @DEFINITIONs not SYMBOLs,
  - it supports an extensible definition types, and
  - filtering based on them.

  PAX has a live browsing [frontend][PAX::@APROPOS].

  Roughly speaking, when NAME or PACKAGE is a SYMBOL, it must match
  the whole @NAME of the definition:

  ```cl-transcript (:dynenv dref-std-env)
  (dref-apropos 'method :package :dref :external-only t)
  ==> (#<DREF METHOD CLASS> #<DREF METHOD LOCATIVE>)
  ```

  On the other hand, when NAME or PACKAGE is a STRING, they are
  matched as substrings to the definition's name PRINC-TO-STRINGed:

  ```cl-transcript (:dynenv dref-std-env)
  (dref-apropos \"method\" :package :dref :external-only t)
  ==> (#<DREF SETF-METHOD LOCATIVE> #<DREF METHOD CLASS>
  -->  #<DREF METHOD LOCATIVE> #<DREF METHOD-COMBINATION CLASS>
  -->  #<DREF METHOD-COMBINATION LOCATIVE>)
  ```

  Definitions that are not of DTYPE (see DTYPEP) are filtered out:

  ```cl-transcript (:dynenv dref-std-env)
  (dref-apropos \"method\" :package :dref :external-only t :dtype 'class)
  ==> (#<DREF METHOD CLASS> #<DREF METHOD-COMBINATION CLASS>)
  ```

  When PACKAGE is :NONE, only non-symbol @NAMES are matched:

  ```
  (dref-apropos \"dref\" :package :none)
  ==> (#<DREF \"DREF\" PACKAGE> #<DREF \"DREF-EXT\" PACKAGE>
  -->  #<DREF \"DREF-TEST\" PACKAGE> #<DREF \"dref\" ASDF/SYSTEM:SYSTEM>
  -->  #<DREF \"dref/full\" ASDF/SYSTEM:SYSTEM>
  -->  #<DREF \"dref/test\" ASDF/SYSTEM:SYSTEM>
  -->  #<DREF \"dref/test-autoload\" ASDF/SYSTEM:SYSTEM>)
  ```

  The exact rules of filtering are as follows. Let `C` be the @NAME of
  the candidate definition from the list of all definitions that we
  are matching against the arguments and denote its string
  representation `(PRINC-TO-STRING C)` with `P`. Note that
  PRINC-TO-STRING does not print the package of symbols. We say that
  two strings _match_ if CASE-SENSITIVE is NIL and they are EQUALP, or
  CASE-SENSITIVE is true and they are EQUAL. CASE-SENSITIVE affects
  _substring_ comparisons too.

  - If NAME is a SYMBOL, then its SYMBOL-NAME must _match_ `P`.

  - If NAME is a STRING, then it must be a _substring_ of `P`.

  - If PACKAGE is :ANY, then `C` must be a SYMBOL.

  - If PACKAGE is :NONE, then `C` must _not_ be a SYMBOL.

  - If PACKAGE is not NIL, :ANY or :NONE, then `C` must be a symbol.

  - If PACKAGE is a [PACKAGE][class], it must be EQ to the
    SYMBOL-PACKAGE of `C`.

  - If PACKAGE is a SYMBOL other than NIL, :ANY and :NONE, then its
    SYMBOL-NAME must _match_ the PACKAGE-NAME or one of the
    PACKAGE-NICKNAMES of SYMBOL-PACKAGE of `C`.

  - If PACKAGE is a STRING, then it must be a _substring_ of the
    PACKAGE-NAME of SYMBOL-PACKAGE of `C`.

  - If EXTERNAL-ONLY and `C` is a symbol, then `C` must be external in
    a matching package.

  - DTYPE matches candidate definition `D` if `(DTYPEP D DTYPE)`.

  If SORT, the returned list is ordered according to SORT-REFERENCES.

  Can be extended via MAP-REFERENCES-OF-TYPE and
  MAP-DEFINITIONS-OF-NAME.")

(autoload:autoload dref:dtypep "dref/full" :arglist "(dref:dref dref:dtype)"
                   :docstring "See if DREF is of DTYPE.

  - _[Atomic locatives][@locative]:_ If DTYPE is a @LOCATIVE-TYPE,
    then it matches definitions with that locative type and its
    locative subtypes.

      Because [CONSTANT][locative] is defined with VARIABLE among its
      [ LOCATIVE-SUPERTYPES] [ define-locative-type]:

      ```cl-transcript (:dynenv dref-std-env)
      (dtypep (dref 'pi 'constant) 'variable)
      => T
      ```

      ```cl-transcript (:dynenv dref-std-env)
      (dtypep (dref 'number 'class) 'type)
      => T
      ```

      It is an error if DTYPE is an ATOM but not a @LOCATIVE-TYPE. On
      the other hand, (the empty) argument list of atomic locatives is
      not checked even if having no arguments makes them
      [invalid][@locative].

  - _[Compound locatives][@locative]:_ Locatives in their compound
    form are validated and must match exactly (under EQUAL, as in
    XREF=).

      ```cl-transcript
      (defparameter *d* (dref 'dref* '(method (t t t))))
      (defparameter *d2* (dref 'dref* '(method :around (t t t))))
      (dtypep *d* 'method)
      => T
      (dtypep *d* '(accessor))
      .. debugger invoked on SIMPLE-ERROR:
      ..   Bad arguments NIL for locative ACCESSOR with lambda list (CLASS-NAME).
      (dtypep *d* '(method (t t t)))
      => T
      (dtypep *d2* '(method (t t t)))
      => NIL
      ```

  - DTYPE may be constructed with [AND][type], [OR][type] and
    [NOT][type] from Lisp types, locative types, full locatives and
    named DTYPEs:

      ```cl-transcript (:dynenv dref-std-env)
      (dtypep (dref 'locate-error 'condition) '(or condition class))
      => T
      (dtypep (dref nil 'type) '(and type (not class)))
      => T
      ```

  - For `(MEMBER &REST OBJS)`, each of OBJS is LOCATEd and DREF is
    matched against them with XREF=:

      ```cl-transcript (:dynenv dref-std-env)
      (dtypep (locate #'print) `(member ,#'print))
      => T
      ```

  - For `(SATISFIES PRED)`, the predicate PRED is funcalled with DREF.

  - DTYPE may be named by DEFINE-DTYPE:

      ```cl-transcript (:dynenv dref-std-env)
      (dtypep (locate #'car) 'top)
      => T
      ```")
